class CountryCodes
  attr_reader :abbr, :name

  def self.all(**kwargs)
    new(**kwargs).all
  end

  def initialize(**kwargs)
    @abbr = kwargs[:abbr]
    @name = kwargs[:name]
  end

  def all
    [
      self.class.new(abbr: 'af', name: 'Afghanistan'),
      self.class.new(abbr: 'ax', name: 'Åland Islands'),
      self.class.new(abbr: 'al', name: 'Albania'),
      self.class.new(abbr: 'dz', name: 'Algeria'),
      self.class.new(abbr: 'as', name: 'American Samoa'),
      self.class.new(abbr: 'ad', name: 'Andorra'),
      self.class.new(abbr: 'ao', name: 'Angola'),
      self.class.new(abbr: 'ai', name: 'Anguilla'),
      self.class.new(abbr: 'aq', name: 'Antarctica'),
      self.class.new(abbr: 'ag', name: 'Antigua and Barbuda'),
      self.class.new(abbr: 'ar', name: 'Argentina'),
      self.class.new(abbr: 'am', name: 'Armenia'),
      self.class.new(abbr: 'aw', name: 'Aruba'),
      self.class.new(abbr: 'au', name: 'Australia'),
      self.class.new(abbr: 'at', name: 'Austria'),
      self.class.new(abbr: 'az', name: 'Azerbaijan'),
      self.class.new(abbr: 'bs', name: 'Bahamas'),
      self.class.new(abbr: 'bh', name: 'Bahrain'),
      self.class.new(abbr: 'bd', name: 'Bangladesh'),
      self.class.new(abbr: 'bb', name: 'Barbados'),
      self.class.new(abbr: 'by', name: 'Belarus'),
      self.class.new(abbr: 'be', name: 'Belgium'),
      self.class.new(abbr: 'bz', name: 'Belize'),
      self.class.new(abbr: 'bj', name: 'Benin'),
      self.class.new(abbr: 'bm', name: 'Bermuda'),
      self.class.new(abbr: 'bt', name: 'Bhutan'),
      self.class.new(abbr: 'bo', name: 'Bolivia'),
      self.class.new(abbr: 'ba', name: 'Bosnia and Herzegovina'),
      self.class.new(abbr: 'bw', name: 'Botswana'),
      self.class.new(abbr: 'bv', name: 'Bouvet Island'),
      self.class.new(abbr: 'br', name: 'Brazil'),
      self.class.new(abbr: 'io', name: 'British Indian Ocean Territory'),
      self.class.new(abbr: 'vg', name: 'British Virgin Islands'),
      self.class.new(abbr: 'bn', name: 'Brunei Darussalam'),
      self.class.new(abbr: 'bg', name: 'Bulgaria'),
      self.class.new(abbr: 'bf', name: 'Burkina Faso'),
      self.class.new(abbr: 'bi', name: 'Burundi'),
      self.class.new(abbr: 'kh', name: 'Cambodia'),
      self.class.new(abbr: 'cm', name: 'Cameroon'),
      self.class.new(abbr: 'ca', name: 'Canada'),
      self.class.new(abbr: 'cv', name: 'Cape Verde'),
      self.class.new(abbr: 'ky', name: 'Cayman Islands'),
      self.class.new(abbr: 'cf', name: 'Central African Republic'),
      self.class.new(abbr: 'td', name: 'Chad'),
      self.class.new(abbr: 'cl', name: 'Chile'),
      self.class.new(abbr: 'cn', name: 'China'),
      self.class.new(abbr: 'cx', name: 'Christmas Island'),
      self.class.new(abbr: 'cc', name: 'Cocos (Keeling) Islands'),
      self.class.new(abbr: 'co', name: 'Colombia'),
      self.class.new(abbr: 'km', name: 'Comoros'),
      self.class.new(abbr: 'cg', name: 'Congo'),
      self.class.new(abbr: 'cd', name: 'Congo, The Democratic Republic of the'),
      self.class.new(abbr: 'ck', name: 'Cook Islands'),
      self.class.new(abbr: 'cr', name: 'Costa Rica'),
      self.class.new(abbr: 'ci', name: "Cote d'Ivoire"),
      self.class.new(abbr: 'hr', name: 'Croatia'),
      self.class.new(abbr: 'cu', name: 'Cuba'),
      self.class.new(abbr: 'cy', name: 'Cyprus'),
      self.class.new(abbr: 'cz', name: 'Czech Republic'),
      self.class.new(abbr: 'dk', name: 'Denmark'),
      self.class.new(abbr: 'dj', name: 'Djibouti'),
      self.class.new(abbr: 'dm', name: 'Dominica'),
      self.class.new(abbr: 'do', name: 'Dominican Republic'),
      self.class.new(abbr: 'ec', name: 'Ecuador'),
      self.class.new(abbr: 'eg', name: 'Egypt'),
      self.class.new(abbr: 'sv', name: 'El Salvador'),
      self.class.new(abbr: 'gq', name: 'Equatorial Guinea'),
      self.class.new(abbr: 'er', name: 'Eritrea'),
      self.class.new(abbr: 'ee', name: 'Estonia'),
      self.class.new(abbr: 'et', name: 'Ethiopia'),
      self.class.new(abbr: 'fk', name: 'Falkland Islands (Malvinas)'),
      self.class.new(abbr: 'fo', name: 'Faroe Islands'),
      self.class.new(abbr: 'fj', name: 'Fiji'),
      self.class.new(abbr: 'fi', name: 'Finland'),
      self.class.new(abbr: 'fr', name: 'France'),
      self.class.new(abbr: 'gf', name: 'French Guiana'),
      self.class.new(abbr: 'pf', name: 'French Polynesia'),
      self.class.new(abbr: 'tf', name: 'French Southern Territories'),
      self.class.new(abbr: 'ga', name: 'Gabon'),
      self.class.new(abbr: 'gm', name: 'Gambia'),
      self.class.new(abbr: 'ge', name: 'Georgia'),
      self.class.new(abbr: 'de', name: 'Germany'),
      self.class.new(abbr: 'gh', name: 'Ghana'),
      self.class.new(abbr: 'gi', name: 'Gibraltar'),
      self.class.new(abbr: 'gb', name: 'United Kingdom (Great Britain)'),
      self.class.new(abbr: 'gr', name: 'Greece'),
      self.class.new(abbr: 'gl', name: 'Greenland'),
      self.class.new(abbr: 'gd', name: 'Grenada'),
      self.class.new(abbr: 'gp', name: 'Guadeloupe'),
      self.class.new(abbr: 'gu', name: 'Guam'),
      self.class.new(abbr: 'gt', name: 'Guatemala'),
      self.class.new(abbr: 'gg', name: 'Guernsey'),
      self.class.new(abbr: 'gw', name: 'Guinea-Bissau'),
      self.class.new(abbr: 'gn', name: 'Guinea'),
      self.class.new(abbr: 'gy', name: 'Guyana'),
      self.class.new(abbr: 'ht', name: 'Haiti'),
      self.class.new(abbr: 'hm', name: 'Heard Island and McDonald Islands'),
      self.class.new(abbr: 'hn', name: 'Honduras'),
      self.class.new(abbr: 'hk', name: 'Hong Kong'),
      self.class.new(abbr: 'hu', name: 'Hungary'),
      self.class.new(abbr: 'is', name: 'Iceland'),
      self.class.new(abbr: 'in', name: 'India'),
      self.class.new(abbr: 'id', name: 'Indonesia'),
      self.class.new(abbr: 'ir', name: 'Iran, Islamic Republic of'),
      self.class.new(abbr: 'iq', name: 'Iraq'),
      self.class.new(abbr: 'ie', name: 'Ireland'),
      self.class.new(abbr: 'im', name: 'Isle of Man'),
      self.class.new(abbr: 'il', name: 'Israel'),
      self.class.new(abbr: 'it', name: 'Italy'),
      self.class.new(abbr: 'jm', name: 'Jamaica'),
      self.class.new(abbr: 'jp', name: 'Japan'),
      self.class.new(abbr: 'je', name: 'Jersey'),
      self.class.new(abbr: 'jo', name: 'Jordan'),
      self.class.new(abbr: 'kz', name: 'Kazakhstan'),
      self.class.new(abbr: 'ke', name: 'Kenya'),
      self.class.new(abbr: 'ki', name: 'Kiribati'),
      self.class.new(abbr: 'kp', name: "Korea, Democratic People's Republic of (North)"),
      self.class.new(abbr: 'kr', name: 'Korea, Republic of (South)'),
      self.class.new(abbr: 'xkv', name: 'Kosovo'),
      self.class.new(abbr: 'kw', name: 'Kuwait'),
      self.class.new(abbr: 'kg', name: 'Kyrgyzstan'),
      self.class.new(abbr: 'la', name: "Lao People's Democratic Republic"),
      self.class.new(abbr: 'lv', name: 'Latvia'),
      self.class.new(abbr: 'lb', name: 'Lebanon'),
      self.class.new(abbr: 'ls', name: 'Lesotho'),
      self.class.new(abbr: 'lr', name: 'Liberia'),
      self.class.new(abbr: 'ly', name: 'Libyan Arab Jamahiriya'),
      self.class.new(abbr: 'li', name: 'Liechtenstein'),
      self.class.new(abbr: 'lt', name: 'Lithuania'),
      self.class.new(abbr: 'lu', name: 'Luxembourg'),
      self.class.new(abbr: 'mo', name: 'Macao'),
      self.class.new(abbr: 'mg', name: 'Madagascar'),
      self.class.new(abbr: 'mw', name: 'Malawi'),
      self.class.new(abbr: 'my', name: 'Malaysia'),
      self.class.new(abbr: 'mv', name: 'Maldives'),
      self.class.new(abbr: 'ml', name: 'Mali'),
      self.class.new(abbr: 'mt', name: 'Malta'),
      self.class.new(abbr: 'mh', name: 'Marshall Islands'),
      self.class.new(abbr: 'mq', name: 'Martinique'),
      self.class.new(abbr: 'mr', name: 'Mauritania'),
      self.class.new(abbr: 'mu', name: 'Mauritius'),
      self.class.new(abbr: 'yt', name: 'Mayotte'),
      self.class.new(abbr: 'mx', name: 'Mexico'),
      self.class.new(abbr: 'fm', name: 'Micronesia, Federated States of'),
      self.class.new(abbr: 'md', name: 'Moldova, Republic of'),
      self.class.new(abbr: 'mc', name: 'Monaco'),
      self.class.new(abbr: 'mn', name: 'Mongolia'),
      self.class.new(abbr: 'me', name: 'Montenegro'),
      self.class.new(abbr: 'ms', name: 'Montserrat'),
      self.class.new(abbr: 'ma', name: 'Morocco'),
      self.class.new(abbr: 'mz', name: 'Mozambique'),
      self.class.new(abbr: 'mm', name: 'Myanmar'),
      self.class.new(abbr: 'na', name: 'Namibia'),
      self.class.new(abbr: 'nr', name: 'Nauru'),
      self.class.new(abbr: 'np', name: 'Nepal'),
      self.class.new(abbr: 'an', name: 'Netherlands Antilles'),
      self.class.new(abbr: 'nl', name: 'Netherlands'),
      self.class.new(abbr: 'nc', name: 'New Caledonia'),
      self.class.new(abbr: 'nz', name: 'New Zealand'),
      self.class.new(abbr: 'ni', name: 'Nicaragua'),
      self.class.new(abbr: 'ne', name: 'Niger'),
      self.class.new(abbr: 'ng', name: 'Nigeria'),
      self.class.new(abbr: 'nu', name: 'Niue'),
      self.class.new(abbr: 'nf', name: 'Norfolk Island'),
      self.class.new(abbr: 'mk', name: 'North Macedonia'),
      self.class.new(abbr: 'mp', name: 'Northern Mariana Islands'),
      self.class.new(abbr: 'no', name: 'Norway'),
      self.class.new(abbr: 'om', name: 'Oman'),
      self.class.new(abbr: 'pk', name: 'Pakistan'),
      self.class.new(abbr: 'pw', name: 'Palau'),
      self.class.new(abbr: 'ps', name: 'Palestinian Territory, Occupied'),
      self.class.new(abbr: 'pa', name: 'Panama'),
      self.class.new(abbr: 'pg', name: 'Papua New Guinea'),
      self.class.new(abbr: 'py', name: 'Paraguay'),
      self.class.new(abbr: 'pe', name: 'Peru'),
      self.class.new(abbr: 'ph', name: 'Philippines'),
      self.class.new(abbr: 'pn', name: 'Pitcairn'),
      self.class.new(abbr: 'pl', name: 'Poland'),
      self.class.new(abbr: 'pt', name: 'Portugal'),
      self.class.new(abbr: 'pr', name: 'Puerto Rico'),
      self.class.new(abbr: 'qa', name: 'Qatar'),
      self.class.new(abbr: 're', name: 'Reunion'),
      self.class.new(abbr: 'ro', name: 'Romania'),
      self.class.new(abbr: 'ru', name: 'Russian Federation'),
      self.class.new(abbr: 'rw', name: 'Rwanda'),
      self.class.new(abbr: 'sh', name: 'Saint Helena'),
      self.class.new(abbr: 'kn', name: 'Saint Kitts and Nevis'),
      self.class.new(abbr: 'lc', name: 'Saint Lucia'),
      self.class.new(abbr: 'pm', name: 'Saint Pierre and Miquelon'),
      self.class.new(abbr: 'vc', name: 'Saint Vincent and the Grenadines'),
      self.class.new(abbr: 'ws', name: 'Samoa'),
      self.class.new(abbr: 'sm', name: 'San Marino'),
      self.class.new(abbr: 'st', name: 'Sao Tome and Principe'),
      self.class.new(abbr: 'sa', name: 'Saudi Arabia'),
      self.class.new(abbr: 'sn', name: 'Senegal'),
      self.class.new(abbr: 'rs', name: 'Serbia'),
      self.class.new(abbr: 'sc', name: 'Seychelles'),
      self.class.new(abbr: 'sl', name: 'Sierra Leone'),
      self.class.new(abbr: 'sg', name: 'Singapore'),
      self.class.new(abbr: 'sk', name: 'Slovakia'),
      self.class.new(abbr: 'si', name: 'Slovenia'),
      self.class.new(abbr: 'sb', name: 'Solomon Islands'),
      self.class.new(abbr: 'so', name: 'Somalia'),
      self.class.new(abbr: 'za', name: 'South Africa'),
      self.class.new(abbr: 'gs', name: 'South Georgia and the South Sandwich Islands'),
      self.class.new(abbr: 'es', name: 'Spain'),
      self.class.new(abbr: 'lk', name: 'Sri Lanka'),
      self.class.new(abbr: 'sd', name: 'Sudan'),
      self.class.new(abbr: 'sr', name: 'Suriname'),
      self.class.new(abbr: 'sj', name: 'Svalbard and Jan Mayen'),
      self.class.new(abbr: 'sz', name: 'Swaziland'),
      self.class.new(abbr: 'se', name: 'Sweden'),
      self.class.new(abbr: 'ch', name: 'Switzerland'),
      self.class.new(abbr: 'sy', name: 'Syrian Arab Republic'),
      self.class.new(abbr: 'tw', name: 'Taiwan, Province of China'),
      self.class.new(abbr: 'tj', name: 'Tajikistan'),
      self.class.new(abbr: 'tz', name: 'Tanzania, United Republic of'),
      self.class.new(abbr: 'th', name: 'Thailand'),
      self.class.new(abbr: 'tl', name: 'Timor-Leste'),
      self.class.new(abbr: 'tg', name: 'Togo'),
      self.class.new(abbr: 'tk', name: 'Tokelau'),
      self.class.new(abbr: 'to', name: 'Tonga'),
      self.class.new(abbr: 'tt', name: 'Trinidad and Tobago'),
      self.class.new(abbr: 'tn', name: 'Tunisia'),
      self.class.new(abbr: 'tr', name: 'Turkey'),
      self.class.new(abbr: 'tm', name: 'Turkmenistan'),
      self.class.new(abbr: 'tc', name: 'Turks and Caicos Islands'),
      self.class.new(abbr: 'tv', name: 'Tuvalu'),
      self.class.new(abbr: 'ug', name: 'Uganda'),
      self.class.new(abbr: 'ua', name: 'Ukraine'),
      self.class.new(abbr: 'ae', name: 'United Arab Emirates'),
      self.class.new(abbr: 'gb', name: 'United Kingdom (Great Britain)'),
      self.class.new(abbr: 'um', name: 'United States Minor Outlying Islands'),
      self.class.new(abbr: 'vi', name: 'U.S. Virgin Islands'),
      self.class.new(abbr: 'us', name: 'United States'),
      self.class.new(abbr: 'uy', name: 'Uruguay'),
      self.class.new(abbr: 'uz', name: 'Uzbekistan'),
      self.class.new(abbr: 'vu', name: 'Vanuatu'),
      self.class.new(abbr: 'va', name: 'Holy See (Vatican City State)'),
      self.class.new(abbr: 've', name: 'Venezuela'),
      self.class.new(abbr: 'vn', name: 'Vietnam'),
      self.class.new(abbr: 'wf', name: 'Wallis and Futuna'),
      self.class.new(abbr: 'eh', name: 'Western Sahara'),
      self.class.new(abbr: 'ye', name: 'Yemen'),
      self.class.new(abbr: 'zm', name: 'Zambia'),
      self.class.new(abbr: 'zw', name: 'Zimbabwe')
    ]
  end
end
